
services:

  db:
    image: postgres:15
    container_name: postgres_db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: weather_db
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - fastapi_network

  app:
    build:
      context: .
    container_name: fastapi_app
    environment:
      - DATABASE_URL=postgresql://user:password@db:5432/weather_db
      - OPENWEATHERMAP_API_KEY=${OPENWEATHERMAP_API_KEY} 
    ports:
      - "8000:8000"
      - "8001:8001" 
    depends_on:
      - db
    networks:
      - fastapi_network

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    ports:
      - "9090:9090"  
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml 
    networks:
      - fastapi_network
    depends_on:
      - app

  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - "3000:3000"  
    networks:
      - fastapi_network
    depends_on:
      - prometheus
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin

networks:
  fastapi_network:
    driver: bridge

volumes:
  db_data: